### ISSUE TITLE
There is no way to delete a server database.

### ISSUE THREAD

**Issue by HolyChoom** [jascaldeira/AOE4-DISCORD-BOT#12]
Hello this is my first pot on GitHub, I'm sorry then if i'm not posting as I should. 

I had an issue today, I thought deleting the bot from our server would reset the database but did it crashed instead.

Since I've deleted the bot, the ladder is still on with the old database but stay stuck and don't show anymore informations or updates on players, we can't register again to update our data either.

Could there is an easy way to add a command "/reset" to clean the database on a server ?

**Comment by jascaldeira** [comment]
I will work on this.

**Comment by jascaldeira** [comment]
Done
